---
# Wazuh server configuration defaults
wazuh_version: "4.12.0"
wazuh_manager_fqdn: "{{ fqdn | default('wazuh.local') }}"
wazuh_api_port: 55000
wazuh_agent_port: 1514
wazuh_agent_enrollment_port: 1515
wazuh_cluster_port: 1516

# Wazuh manager configuration
wazuh_manager_config:
  cluster:
    disabled: "no"
    name: "wazuh"
    node_name: "manager"
    node_type: "master"
    key: "{{ wazuh_cluster_key | default(lookup('password', '/dev/null length=32 chars=ascii_letters,digits')) }}"
    bind_addr: "0.0.0.0"
    nodes:
      - "{{ ansible_default_ipv4.address }}"
    hidden: "no"

# Wazuh API configuration
wazuh_api_users:
  - username: "admin"
    password: "{{ wazuh_api_password | default('SecurePassword123!') }}"

# Indexer configuration
wazuh_indexer_network_host: "0.0.0.0"
wazuh_indexer_cluster_initial_master_nodes:
  - "{{ ansible_hostname }}"

# Dashboard configuration - Bind to all interfaces, control via firewall
wazuh_dashboard_server_host: "0.0.0.0"
wazuh_dashboard_server_port: 5601

# Filebeat configuration
filebeat_output_indexer_hosts:
  - "{{ ansible_default_ipv4.address }}:9200"

# Security settings
wazuh_authd_pass: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"

# Container specific settings
wazuh_container_network: "{{ lxd_network.split('/')[0] }}"
wazuh_container_cidr: "{{ lxd_network }}"
