---
# Ansible Galaxy requirements for Molecule testing
collections:
  - name: community.general
    version: ">=7.0.0"
  - name: community.docker
    version: ">=3.0.0"
  - name: ansible.posix
    version: ">=1.4.0"
  - name: community.crypto
    version: ">=2.0.0"

roles: []