---
galaxy_info:
  author: DHIS2 Server Tools
  description: Wazuh server deployment for DHIS2 LXD containers
  license: BSD
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - security
    - monitoring
    - wazuh
    - siem
    - dhis2

dependencies: []