---
- name: Configure Wazuh API network settings
  ansible.builtin.lineinfile:
    path: /var/ossec/api/configuration/api.yaml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - { regexp: "^  host:", line: "  host: 0.0.0.0" }
    - { regexp: "^  port:", line: "  port: {{ wazuh_api_port }}" }
  notify: restart wazuh-manager

- name: Configure Wazuh API security settings
  ansible.builtin.blockinfile:
    path: /var/ossec/api/configuration/api.yaml
    marker: "# {mark} ANSIBLE MANAGED BLOCK - API Security"
    insertafter: "^https:"
    block: |
      # Enable HTTPS
      enabled: true
      # Certificate paths
      cert: "/var/ossec/api/configuration/ssl/server.crt"
      key: "/var/ossec/api/configuration/ssl/server.key"
  notify: restart wazuh-manager

- name: Ensure API configuration directory has correct permissions
  ansible.builtin.file:
    path: /var/ossec/api/configuration
    owner: root
    group: wazuh
    mode: '0750'
    recurse: yes