---
# Molecule converge playbook - runs the actual deployment
- name: Deploy Wazuh Security Monitoring
  hosts: wazuh
  become: true
  gather_facts: true
  vars:
    # Override for Docker environment
    ansible_connection: docker
    wazuh_manager_fqdn: wazuh-server
    wazuh_container_network: "172.20.0.0"
    wazuh_container_cidr: "172.20.0.0/16"
  roles:
    - role: ../../deploy/roles/wazuh-server

- name: Install Wazuh agents on monitored containers
  hosts: instances
  become: true
  gather_facts: true
  vars:
    # Override for Docker environment
    ansible_connection: docker
    wazuh_manager_ip: wazuh-server
  roles:
    - role: ../../deploy/roles/wazuh-agent
      when: groups['wazuh'] | length > 0