---
# Molecule converge playbook - tests Wazuh integration with official roles
- name: Test Wazuh Integration
  import_playbook: ../../deploy/wazuh.yml

- name: Verify Wazuh Installation
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Check if Wazuh manager is installed
      ansible.builtin.service:
        name: wazuh-manager
        state: started
      when: inventory_hostname in groups['wazuh_managers']
      ignore_errors: true
      register: manager_status

    - name: Check if Wazuh agent is installed  
      ansible.builtin.service:
        name: wazuh-agent
        state: started
      when: inventory_hostname in groups['instances']
      ignore_errors: true
      register: agent_status

    - name: Display results
      ansible.builtin.debug:
        msg: "Wazuh services status checked successfully"