---
# Default Molecule scenario - Basic Wazuh integration test
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml
    ignore-certs: true
    ignore-errors: true

driver:
  name: docker

platforms:
  - name: wazuh-server
    image: ghcr.io/hifis-net/ubuntu-systemd:22.04
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    environment:
      DEBIAN_FRONTEND: noninteractive
    networks:
      - name: dhis2-molecule-net
    published_ports:
      - "55000:55000"  # Wazuh API
      - "1514:1514"    # Wazuh Agent Port
  
  - name: dhis2-instance
    image: ghcr.io/hifis-net/ubuntu-systemd:22.04
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    environment:
      DEBIAN_FRONTEND: noninteractive
    networks:
      - name: dhis2-molecule-net

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: junit, yaml, timer
      stdout_callback: yaml
      bin_ansible_callbacks: true
      host_key_checking: false
      conditional_bare_variables: true
      allow_world_readable_tmpfiles: true
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_ALLOW_BROKEN_CONDITIONALS: True
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        ansible_connection: docker
        enable_wazuh_monitoring: yes
        single_node: true
        
    groups:
      wazuh_managers:
        - wazuh-server
      wazuh_indexers:
        - wazuh-server  
      wazuh_dashboards:
        - wazuh-server
      instances:
        - dhis2-instance

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy