---
- name: Configure container-specific log monitoring
  ansible.builtin.blockinfile:
    path: /var/ossec/etc/ossec.conf
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - Container Monitoring -->"
    insertbefore: "</ossec_config>"
    content: |
      <!-- Container-specific monitoring -->
      <localfile>
        <log_format>syslog</log_format>
        <location>/var/log/lxd/{{ inventory_hostname }}.log</location>
      </localfile>
      
      <!-- Monitor container processes -->
      <localfile>
        <log_format>full_command</log_format>
        <command>ps aux | grep -E "(java|postgres|nginx|apache)" | grep -v grep</command>
        <frequency>300</frequency>
      </localfile>
      
      <!-- Monitor container resources -->
      <localfile>
        <log_format>full_command</log_format>
        <command>df -h | grep -E "/$|/opt"</command>
        <frequency>3600</frequency>
      </localfile>
  notify: restart wazuh-agent

- name: Configure DHIS2-specific monitoring for instances
  ansible.builtin.blockinfile:
    path: /var/ossec/etc/ossec.conf
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - DHIS2 Monitoring -->"
    insertbefore: "</ossec_config>"
    content: |
      <!-- DHIS2 Performance Monitoring -->
      <localfile>
        <log_format>full_command</log_format>
        <command>curl -s http://localhost:8080/api/system/info | jq -r '.contextPath,.version,.revision'</command>
        <frequency>3600</frequency>
      </localfile>
      
      <!-- DHIS2 Active Sessions -->
      <localfile>
        <log_format>full_command</log_format>
        <command>curl -s http://localhost:8080/api/system/sessions | jq -r '.activeSessions'</command>
        <frequency>300</frequency>
      </localfile>
  when: inventory_hostname in groups['instances']
  notify: restart wazuh-agent

- name: Configure PostgreSQL-specific monitoring for databases
  ansible.builtin.blockinfile:
    path: /var/ossec/etc/ossec.conf
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - PostgreSQL Monitoring -->"
    insertbefore: "</ossec_config>"
    content: |
      <!-- PostgreSQL Connection Monitoring -->
      <localfile>
        <log_format>full_command</log_format>
        <command>sudo -u postgres psql -c "SELECT count(*) FROM pg_stat_activity WHERE state = 'active';" -t</command>
        <frequency>300</frequency>
      </localfile>
      
      <!-- PostgreSQL Lock Monitoring -->
      <localfile>
        <log_format>full_command</log_format>
        <command>sudo -u postgres psql -c "SELECT count(*) FROM pg_locks WHERE granted = false;" -t</command>
        <frequency>300</frequency>
      </localfile>
  when: inventory_hostname in groups['databases']
  notify: restart wazuh-agent

- name: Ensure Wazuh agent can read application logs
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0644'
    state: file
  loop:
    - /opt/dhis2/*/logs/dhis.log
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log
  failed_when: false
  when: inventory_hostname in groups['instances'] or inventory_hostname in groups['web']