---
- name: Install Wazuh agent prerequisites
  ansible.builtin.apt:
    name:
      - curl
      - gnupg2
      - apt-transport-https
      - lsb-release
    state: present
    update_cache: yes

- name: Add Wazuh repository key
  ansible.builtin.apt_key:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present

- name: Add Wazuh repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
    state: present
    filename: wazuh

- name: Install Wazuh agent
  ansible.builtin.apt:
    name: wazuh-agent={{ wazuh_agent_version }}-*
    state: present
    update_cache: yes
  environment:
    WAZUH_MANAGER: "{{ wazuh_manager_ip }}"
    WAZUH_AGENT_NAME: "{{ wazuh_agent_name }}"

- name: Configure Wazuh agent
  ansible.builtin.template:
    src: ossec.conf.j2
    dest: /var/ossec/etc/ossec.conf
    owner: root
    group: wazuh
    mode: '0640'
    backup: yes
  notify: restart wazuh-agent

- name: Register agent with manager
  ansible.builtin.shell: |
    /var/ossec/bin/agent-auth -m {{ wazuh_manager_ip }} -p {{ wazuh_enrollment_port }} -A {{ wazuh_agent_name }}
  args:
    creates: /var/ossec/etc/client.keys
  register: agent_registration

- name: Set agent groups
  ansible.builtin.shell: |
    /var/ossec/bin/agent-groups -a -i {{ ansible_hostname }} -g {{ item }}
  loop: "{{ wazuh_agent_groups }}"
  delegate_to: "{{ groups['wazuh'][0] }}"
  when: agent_registration is changed

- name: Enable and start Wazuh agent
  ansible.builtin.systemd:
    name: wazuh-agent
    enabled: yes
    state: started
    daemon_reload: yes

- name: Configure container-specific monitoring
  ansible.builtin.include_tasks: configure-monitoring.yml