---
- name: restart wazuh-manager
  ansible.builtin.systemd:
    name: wazuh-manager
    state: restarted
    daemon_reload: yes

- name: restart wazuh-indexer
  ansible.builtin.systemd:
    name: wazuh-indexer
    state: restarted
    daemon_reload: yes

- name: restart wazuh-dashboard
  ansible.builtin.systemd:
    name: wazuh-dashboard
    state: restarted
    daemon_reload: yes