---
# Wazuh-only scenario - Test just the Wazuh server deployment
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: wazuh-standalone
    image: quay.io/ansible/molecule-ubuntu:22.04
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    environment:
      DEBIAN_FRONTEND: noninteractive
    published_ports:
      - "55001:55000"  # Wazuh API (different port to avoid conflicts)
      - "1515:1514"    # Wazuh Agent Port

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: junit, yaml, timer
      stdout_callback: yaml
      host_key_checking: false
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        ansible_connection: docker
        wazuh_version: "4.12.0"
        wazuh_api_password: "StandaloneTest123!"
        wazuh_authd_pass: "StandaloneAuth123!"
        wazuh_container_network: "172.21.0.0"
        wazuh_container_cidr: "172.21.0.0/16"
        
    groups:
      wazuh:
        - wazuh-standalone

verifier:
  name: ansible

scenario:
  name: wazuh-only
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy