---
- name: Prepare Wazuh standalone environment
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - python3
          - curl
          - wget
          - gnupg
          - apt-transport-https
          - software-properties-common
          - openjdk-11-jdk
        state: present

    - name: Create Wazuh user
      ansible.builtin.user:
        name: wazuh
        system: yes
        shell: /bin/false
        home: /var/ossec

    - name: Create required directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /var/ossec
        - /etc/wazuh
        - /var/log/wazuh