---
# Molecule scenario for testing official Wazuh Ansible roles
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    force: true

driver:
  name: docker

platforms:
  - name: wazuh-single-node
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    environment:
      DEBIAN_FRONTEND: noninteractive
    # Note: Ports not published for security - internal access only
    groups:
      - wazuh_managers
      - wazuh_indexers
      - wazuh_dashboards

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: junit, yaml, timer
      stdout_callback: yaml
      host_key_checking: false
      interpreter_python: auto_silent
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        single_node: true
        wazuh_manager_version: "4.12.0-1"
        indexer_jvm_heap_size: "512m"  # Reduced for testing
        generate_certificates: true
  playbooks:
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible

scenario:
  name: wazuh
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy